sudo: required
dist: xenial
language: python
python:
  - "3.6"

jobs:
  include:

#    - stage: code quality
#      name: "pylint lbrynet"
#      install:
#        - pip install pylint
#        - pip install git+https://github.com/lbryio/torba.git
#        - pip install git+https://github.com/lbryio/lbryschema.git
#        - pip install -e .
#      script: pylint lbrynet
#
#    - stage: test
#      name: "Unit Tests"
#      install:
#        - pip install coverage
#        - pip install git+https://github.com/lbryio/torba.git
#        - pip install git+https://github.com/lbryio/lbryschema.git
#        - pip install -e .[test]
#      script: HOME=/tmp coverage run --source=lbrynet -m twisted.trial tests.unit
#      #script: HOME=/tmp coverage run --source=lbrynet -m twisted.trial tests.functional tests.unit
#      after_success:
#        - bash <(curl -s https://codecov.io/bash)
#
#    - name: "Integration Tests"
#      install:
#        - pip install tox-travis coverage
#        - pushd .. && git clone https://github.com/lbryio/electrumx.git --branch lbryumx && popd
#        - pushd .. && git clone https://github.com/lbryio/orchstr8.git && popd
#        - pushd .. && git clone https://github.com/lbryio/lbryschema.git && popd
#        - pushd .. && git clone https://github.com/lbryio/lbryumx.git && popd
#        - pushd .. && git clone https://github.com/lbryio/torba.git && popd
#      script: tox
#      after_success:
#        - coverage combine tests/
#        - bash <(curl -s https://codecov.io/bash)
#
#    - stage: build
#      name: "Windows"
#      services:
#        - docker
#      install:
#        - docker pull cdrx/pyinstaller-windows:python3-32bit
#      script:
#        - docker run -v "$(pwd):/src/lbry" cdrx/pyinstaller-windows:python3-32bit lbry/scripts/wine_build.sh
#      addons:
#        artifacts:
#          working_dir: dist
#          paths:
#            - lbry.exe
#          target_paths:
#            - /daemon/build-${TRAVIS_BUILD_NUMBER}_commit-${TRAVIS_COMMIT:0:7}_branch-${TRAVIS_BRANCH}$([ ! -z ${TRAVIS_TAG} ] && echo _tag-${TRAVIS_TAG})/win
#
#    - name: "Linux"
#      install:
#        - pip install pyinstaller
#        - pip install git+https://github.com/lbryio/torba.git
#        - pip install git+https://github.com/lbryio/lbryschema.git
#        - pip install -e .
#      script:
#        - pyinstaller -F -n lbry lbrynet/cli.py
#        - ./dist/lbry --version
#      addons:
#        artifacts:
#          working_dir: dist
#          paths:
#            - lbry
#          target_paths:
#            - /daemon/build-${TRAVIS_BUILD_NUMBER}_commit-${TRAVIS_COMMIT:0:7}_branch-${TRAVIS_BRANCH}$([ ! -z ${TRAVIS_TAG} ] && echo _tag-${TRAVIS_TAG})/linux

    - stage: build
      name: "Mac"
      os: osx
      osx_image: xcode9.4
      language: generic
      install:
        - brew install python
        - pip install pyinstaller
        - pip install git+https://github.com/lbryio/torba.git
        - pip install git+https://github.com/lbryio/lbryschema.git
        - pip install -e .
      script:
        - pyinstaller -F -n lbry lbrynet/cli.py
        - ./dist/lbry --version
      addons:
        artifacts:
          working_dir: dist
          paths:
            - lbry
          target_paths:
            - /daemon/build-${TRAVIS_BUILD_NUMBER}_commit-${TRAVIS_COMMIT:0:7}_branch-${TRAVIS_BRANCH}$([ ! -z ${TRAVIS_TAG} ] && echo _tag-${TRAVIS_TAG})/mac

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/Library/Caches/pip
    - $TRAVIS_BUILD_DIR/.tox
